In [1]:
cd /Users/apple/Documents/ML_Project/simple_esn

/Users/apple/Documents/ML_Project/simple_esn


In [3]:
from simple_esn import SimpleESN
import numpy as np
n_samples, n_features = 10, 5
np.random.seed(0)
X = np.random.randn(n_samples, n_features)
esn = SimpleESN(n_readout = 2)
echoes = esn.fit_transform(X)

In [4]:
X

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [5]:
esn.readout_idx_

array([13, 96])

In [10]:
print(echoes)
print(echoes.shape)

[[-0.43240768  0.17736167]
 [-0.02714532  0.46169146]
 [-0.16302795  0.45552631]
 [ 0.20719069  0.5458634 ]
 [-0.03676832  0.57027169]
 [ 0.02758655  0.66886911]
 [-0.040953    0.47978527]
 [-0.16637389  0.22493491]
 [ 0.38177896  0.48910255]
 [ 0.08385342 -0.07561416]]
(10, 2)


In [7]:
%run test_simple_esn.py

In [8]:
from simple_esn import SimpleESN
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
import sklearn.svm as svm

# Pick your classifier
pipeline = Pipeline([('esn', SimpleESN(n_readout=1000)),
                     ('svr', svm.SVR())])
parameters = {
    'esn__weight_scaling': [0.5, 1.0],
    'svr__C': [1, 10]
}
grid_search = GridSearchCV(pipeline, parameters)
grid_search.fit(X_train, y_train)

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/Users/apple/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-6c6959051b07>", line 14, in <module>
    grid_search.fit(X_train, y_train)
NameError: name 'X_train' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2039, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/apple/an

NameError: name 'X_train' is not defined